### PR TITLE
Update default jdkVersion to 17

### PR DESCRIPTION
**Pull request by TramPamPam**

### CODE REVIEW

**Review by VladStarikovEk — APPROVED** [review]

**Comment by mcfedr** [comment]
you need to adjust the ci script as well, https://github.com/ekreative/android-docker/blob/master/.github/workflows/release-image.yml#L79

**Comment by mcfedr** [comment]
and the script that generates all the other files, https://github.com/ekreative/android-docker/blob/master/update.sh

**Comment by mcfedr** [comment]
and the list of images in the readme, https://github.com/ekreative/android-docker/blob/master/README.md

**Comment by mcfedr** [comment]
see https://github.com/ekreative/android-docker/pull/17

**Pull request closed without merging**
